-- MySQL Script generated by MySQL Workbench
-- Mon Aug  6 16:40:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema archivos_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema archivos_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `archivos_db` DEFAULT CHARACTER SET utf8 ;
USE `archivos_db` ;

-- -----------------------------------------------------
-- Table `archivos_db`.`datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archivos_db`.`datos` (
  `iddatos` INT NOT NULL AUTO_INCREMENT,
  `titulo_img` VARCHAR(75) NULL,
  `nombre_dir` VARCHAR(75) NULL,
  `usuario` VARCHAR(45) NULL,
  `descripcion_subida` VARCHAR(75) NULL,
  PRIMARY KEY (`iddatos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
